#!/usr/bin/env bash
# install-strand-cloud.sh -- Deploy the strand-cloud binary with systemd service
#
# Expected environment variables:
#   STRAND_ENV           - Environment (dev/staging/prod)
#   STRAND_DOMAIN        - Domain name
#   STRAND_NODE_ROLE     - Node role (control-plane/worker)
#   STRAND_NODE_INDEX    - Node index within its role group
#   STRAND_CP_COUNT      - Total control-plane node count (for CP nodes)
#   STRAND_CP_ENDPOINT   - Control-plane private IP (for worker nodes)
set -euo pipefail

STRAND_ENV="${STRAND_ENV:-dev}"
STRAND_DOMAIN="${STRAND_DOMAIN:-localhost}"
STRAND_NODE_ROLE="${STRAND_NODE_ROLE:-worker}"
STRAND_NODE_INDEX="${STRAND_NODE_INDEX:-0}"
STRAND_CP_COUNT="${STRAND_CP_COUNT:-1}"
STRAND_CP_ENDPOINT="${STRAND_CP_ENDPOINT:-127.0.0.1}"

INSTALL_DIR="/opt/strand"
CONFIG_DIR="/opt/strand/config"
DATA_DIR="/opt/strand/data"
LOG_DIR="/var/log/strand"

echo "==> Installing Strand Cloud (role=${STRAND_NODE_ROLE}, env=${STRAND_ENV})..."

# Ensure directories exist
mkdir -p "${INSTALL_DIR}/bin" "${CONFIG_DIR}" "${DATA_DIR}" "${LOG_DIR}"

# Download the strand-cloud binary from releases
# In production, this would come from a private artifact store or CI/CD.
# For now we create a placeholder that the CI pipeline will replace.
BINARY_URL="https://releases.strand-protocol.net/${STRAND_ENV}/strand-cloud-linux-amd64"
if curl -fsSL --head "${BINARY_URL}" > /dev/null 2>&1; then
    curl -fsSL "${BINARY_URL}" -o "${INSTALL_DIR}/bin/strand-cloud"
else
    echo "WARN: Binary not available at ${BINARY_URL}, creating placeholder."
    echo '#!/bin/bash' > "${INSTALL_DIR}/bin/strand-cloud"
    echo 'echo "strand-cloud placeholder -- replace with real binary"' >> "${INSTALL_DIR}/bin/strand-cloud"
    echo 'sleep infinity' >> "${INSTALL_DIR}/bin/strand-cloud"
fi
chmod +x "${INSTALL_DIR}/bin/strand-cloud"

# Generate the node configuration
if [ "${STRAND_NODE_ROLE}" = "control-plane" ]; then
    # Control plane configuration
    cat > "${CONFIG_DIR}/strand-cloud.yaml" <<CPCONF
# Strand Cloud -- Control Plane Configuration
# Auto-generated by install-strand-cloud.sh

environment: ${STRAND_ENV}
node:
  role: control-plane
  index: ${STRAND_NODE_INDEX}
  hostname: $(hostname)
  overlay_port: 6477

api_server:
  listen: 0.0.0.0:8080
  tls:
    enabled: false  # TLS terminated at Caddy reverse proxy
  cors:
    allowed_origins:
      - "https://*.${STRAND_DOMAIN}"
  rate_limit:
    requests_per_second: 100
    burst: 200

auth:
  api_key:
    enabled: true
  mic:
    enabled: true
  oidc:
    enabled: false  # Enable when Kratos is ready

CPCONF

    # Set store backend based on environment
    if [ "${STRAND_ENV}" = "dev" ]; then
        STORE_BACKEND="memory"
    else
        STORE_BACKEND="etcd"
    fi

    cat >> "${CONFIG_DIR}/strand-cloud.yaml" <<STORECONF
store:
  backend: ${STORE_BACKEND}
STORECONF

    if [ "${STRAND_ENV}" != "dev" ]; then
        cat >> "${CONFIG_DIR}/strand-cloud.yaml" <<ETCDCONF
  etcd:
    endpoints:
      - "http://127.0.0.1:2379"
    dial_timeout: 5s
    username: ""
    password: ""
ETCDCONF
    fi

    cat >> "${CONFIG_DIR}/strand-cloud.yaml" <<CPCONF2

fleet:
  reconcile_interval: 30s
  heartbeat_timeout: 60s
  leader_election:
    enabled: $([ "${STRAND_CP_COUNT}" -gt 1 ] && echo "true" || echo "false")
    lease_duration: 15s
    renew_deadline: 10s

ca:
  enabled: true
  key_algorithm: ed25519
  mic_validity: 8760h  # 1 year
  storage_dir: ${DATA_DIR}/ca

metrics:
  enabled: true
  listen: 0.0.0.0:9090
  path: /metrics

logging:
  level: info
  format: json
  output: ${LOG_DIR}/strand-cloud.log
CPCONF2

else
    # Worker node configuration (agent mode)
    cat > "${CONFIG_DIR}/strand-cloud.yaml" <<WKCONF
# Strand Cloud -- Worker Agent Configuration
# Auto-generated by install-strand-cloud.sh

environment: ${STRAND_ENV}
node:
  role: worker
  index: ${STRAND_NODE_INDEX}
  hostname: $(hostname)
  overlay_port: 6477

agent:
  control_plane_endpoint: "http://${STRAND_CP_ENDPOINT}:8080"
  heartbeat_interval: 10s
  registration:
    auto_register: true
    labels:
      environment: ${STRAND_ENV}
      region: PHX

api_server:
  listen: 0.0.0.0:8080
  tls:
    enabled: false

metrics:
  enabled: true
  listen: 0.0.0.0:9090
  path: /metrics

logging:
  level: info
  format: json
  output: ${LOG_DIR}/strand-cloud.log
WKCONF
fi

# Set ownership
chown -R strand:strand "${INSTALL_DIR}" "${LOG_DIR}"

# Create systemd service for control-plane
if [ "${STRAND_NODE_ROLE}" = "control-plane" ]; then
    cat > /etc/systemd/system/strand-cloud.service <<SVCEOF
[Unit]
Description=Strand Cloud Control Plane
Documentation=https://docs.strand-protocol.net/
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=strand
Group=strand
ExecStart=${INSTALL_DIR}/bin/strand-cloud serve \
    --config ${CONFIG_DIR}/strand-cloud.yaml
Restart=on-failure
RestartSec=5
LimitNOFILE=1048576
LimitNPROC=65535

# Environment file for secrets
EnvironmentFile=-/etc/strand/secrets.env

StandardOutput=append:${LOG_DIR}/strand-cloud.log
StandardError=append:${LOG_DIR}/strand-cloud-error.log

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${DATA_DIR} ${LOG_DIR}
PrivateTmp=true

# Watchdog
WatchdogSec=60

[Install]
WantedBy=multi-user.target
SVCEOF

else
    # Systemd service for worker agent
    cat > /etc/systemd/system/strand-agent.service <<SVCEOF
[Unit]
Description=Strand Cloud Worker Agent
Documentation=https://docs.strand-protocol.net/
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=strand
Group=strand
ExecStart=${INSTALL_DIR}/bin/strand-cloud agent \
    --config ${CONFIG_DIR}/strand-cloud.yaml
Restart=on-failure
RestartSec=5
LimitNOFILE=1048576
LimitNPROC=65535

EnvironmentFile=-/etc/strand/secrets.env

StandardOutput=append:${LOG_DIR}/strand-agent.log
StandardError=append:${LOG_DIR}/strand-agent-error.log

NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${DATA_DIR} ${LOG_DIR}
PrivateTmp=true

WatchdogSec=60

[Install]
WantedBy=multi-user.target
SVCEOF
fi

# Create secrets environment file placeholder
touch /etc/strand/secrets.env
chmod 600 /etc/strand/secrets.env
cat > /etc/strand/secrets.env <<SECRETS
# Strand secrets -- managed by Pulumi / external secrets manager
# STRAND_API_KEY=
# STRAND_DB_PASSWORD=
# STRAND_CA_PRIVATE_KEY=
SECRETS

# Enable and start the service
systemctl daemon-reload

if [ "${STRAND_NODE_ROLE}" = "control-plane" ]; then
    systemctl enable strand-cloud
    systemctl start strand-cloud
    echo "==> Strand Cloud control-plane service started."
    echo "    Config: ${CONFIG_DIR}/strand-cloud.yaml"
    echo "    API: http://0.0.0.0:8080"
else
    systemctl enable strand-agent
    systemctl start strand-agent
    echo "==> Strand Cloud worker agent started."
    echo "    Config: ${CONFIG_DIR}/strand-cloud.yaml"
    echo "    Control plane: http://${STRAND_CP_ENDPOINT}:8080"
fi
